# Generated by Django 3.1.4 on 2021-01-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
